config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'

  resources :places, only: [ :show, :index ] do
    resources :matches, only: [ :create]
  end

  get "users/:id/matches", to: "matches#user_matches", as: :user_matches

  get "load", to: "pages#load", as: :load

# DEMO Landing Page (without login)
  get "demo", to: "pages#demo", as: :demo

  get "search", to: "pages#search"
  #  get "places/:id/matches", to: "matches#destroy"



  resources :matches, only: [:index, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :user
  belongs_to :place

  validates :place, uniqueness: { scope: [:user, :status] }
end

app/models/place.rb
class Place < ApplicationRecord
  # GOOGLE_API_KEY = "AIzaSyCphxuvUrZsX8xRq5rA9TZy-cgYTSHvCyU"

  has_many :matches

  validates :name, uniqueness: true

 # scope :open_now, -> (day, time) { where("weekday = ? AND open_time <= ? AND close_time > ?", day, time, time) }

  def image_url
    # photo_reference = self.google_data["photos"][0]["photo_reference"]

    # randon_number = rand(1..4).to_s
    # api_key = ENV['google_api_key_' + randon_number]

    # url = "https://maps.googleapis.com/maps/api/place/photo?maxwidth=400&photoreference=#{photo_reference}&key=#{api_key}"
    url = "https://loremflickr.com/600/400/bar,cocktail?lock=#{self.id}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]

  has_many :matches

  # [...]
  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :gotoplaces

  def gotoplaces
    redirect_to places_path if current_user and root_path == request.path
  end

  def default_url_options
    { host: ENV["HOST"] || "localhost:3000" }
  end

end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

  skip_before_action :verify_authenticity_token
  skip_before_action :authenticate_user!


  def create

    status = params["status"] || params["place"]["status"]

   params.has_key?("username") ? user = params["username"].to_i : user = current_user.id
     @match = Match.new(user_id: user, place_id: params["place_id"].to_i, status: status)
     saved = @match.save

    redirect_to places_path(kind: params[:kind])
  end

  def user_matches
    @user_matches = Match.where(user_id: current_user.id, status: "yes").order("created_at desc")
  end

  def update
  end

  def destroy
    user_id = current_user.id
    # arbi = Match.where(user_id: current_user, place_id: params[:place_id]).first
    arbi = Match.find(params[:id])
    arbi.destroy
    redirect_to "/users/#{user_id}/matches"
    # render :user_matches
    # respond_to do |format|
    #   format.html { redirect_to "users/#{user_id}/matches", notice: 'Match was successfully destroyed.' }
    # end
  end

  def index

  end

  def show
  end

  private

  def matches_params
    params.require(:place).permit(:place_id, :status)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @navbar = true
  end

  def load
  end

  def demo
    @navbar = true
  end

  def search
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

  def index
    @places = []
    already_matches_place_ids = current_user.matches.where(status: "yes").map(&:place_id)

    Place.where.not(id: already_matches_place_ids).each do |place|
      next if params[:kind].present? and not place.google_data["types"].include? params[:kind]
      next if not place.google_data["opening_hours"]
      next if not place.google_data["opening_hours"]["open_now"]
      next if not place.google_data["photos"][0]

      @places << place
    end
    @places = @places.shuffle.first(10)
  end


  def show
    @place = Place.find(params[:id])
  end

  def show_image
    photo_reference = @place.google_data["photos"][0]["photo_reference"]
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <%= favicon_link_tag %>

  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Post Meridiem</title>

<!-- Facebook Card data -->
<meta property="og:title" content="<%= meta_title %>" />
<meta property="og:type" content="website" />
<meta property="og:url" content="<%= request.original_url %>" />
<meta property="og:image" content="<%= meta_image %>" />
<meta property="og:description" content="<%= meta_description %>" />
<meta property="og:site_name" content="<%= meta_title %>" />

<!-- Twitter Card data -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
<meta name="twitter:title" content="<%= meta_title %>">
<meta name="twitter:description" content="<%= meta_description %>">
<meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
<meta name="twitter:image:src" content="<%= meta_image %>">









  <%= csrf_meta_tags %>
  <%= include_gon %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>

  <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->

  <!-- Import GoogleFONT -->
  <link href="https://fonts.googleapis.com/css?family=Quicksand:400,500,700" rel="stylesheet">

  <!-- Import FONTAWESOME -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">

  <!-- Import BOOTSTRAP -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

  <script src="https://hammerjs.github.io/dist/hammer.min.js"></script>

  <script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>

</head>
<body>

  <%= render 'shared/navbar' unless @navbar %>
  <%= render 'shared/flashes' %>
  <%= yield %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_pack_tag 'application' %>



  <script>
    <% if current_user  %>
    window.username = <%= current_user.id  %>
    <% end %>
  </script>



</body>
</html>

app/views/matches/index.html.erb
<h1>matche#index</h1>
<p>Find me in app/views/matches/index.html.erb</p>

app/views/matches/user_matches.html.erb
<div class="matches-wrapper">
  <div class="user-welcome">
    <h1>Hello <%= current_user.email.split("@")[0].capitalize  %> :)</h1>
    <p>The places you love:</p>
  </div>

  <div class="card-matches">
    <div class="clearfix">
    <% @user_matches.each do |single_match| %>
      <% if single_match.place.google_data["photos"][0] %>

      <div class="col-xs-6">
        <div class="main-card-matches">

          <%= link_to place_path(single_match.place) do %>
           <div class="photo-card" style="background: url('<%= asset_url single_match.place.image_url %>') no-repeat;"></div>
          <% end %>


          <h3 class="card-category">
            <%= link_to single_match.place.name, place_path(single_match.place) %>

            </h3>
          <div class="wrapper-heart">
            <div class="delete-heart">

              <%= link_to match_path(single_match), method: :delete do %>
                  <i class="far fa-trash-alt"></i>
              <% end %>

            </div>
            <div class="icon-matches">
              <div><%= single_match.place.matches.count %> </div>
              <i class="fa fa-heart" style="size:1px";></i>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    <% end %>
  </div> <!-- / row -->


  </div>
</div>

app/views/pages/demo.html.erb
<div class="video-back">
  <video playsinline autoplay muted loop poster="<%= image_path('background.png') %>" id="doge">
    <source src="https://www.videvo.net/videvo_files/converted/2014_03/preview/Beer_Bubbles_300314__Videvo.mov34510.webm" type="video/webm">
    <source src="https://www.videvo.net/videvo_files/converted/2014_03/videos/Beer_Bubbles_300314__Videvo.mov34510.mp4" type="video/mp4">
    </video>
  </div>


  <div class="home-wrapper">
    <div class="home-content">
      <div id="logo" class="text-center">
        <%= image_tag("Logo pink-1.png",
        alt: "Post Meridiem Logo") %>
      </div>

      <h1 class="text-center">
        your perfect evening<br>
        just around the corner
      </h1>

      <div class="container">
        <div class="row up-down-margin">
          <div class="col-xs-8 col-xs-offset-2">
            <div class="row row-first">
              <%= link_to "LOG IN", new_user_session_path, class: "btn-danger btn-md" %>

              <%= link_to "SIGN UP", new_user_registration_path, class: "btn-danger btn-md" %>
            </div>
          </div>
        </div>

        <div class="row">


          <%= link_to search_path, class: "facebookLoginBtnMain xLargeFacebookBtn" do %>
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 216 216" class="_55a2"><path fill="white" d="
            M204.1 0H11.9C5.3 0 0 5.3 0 11.9v192.2c0 6.6 5.3 11.9 11.9
            11.9h103.5v-83.6H87.2V99.8h28.1v-24c0-27.9 17-43.1 41.9-43.1
            11.9 0 22.2.9 25.2 1.3v29.2h-17.3c-13.5 0-16.2 6.4-16.2
            15.9v20.8h32.3l-4.2 32.6h-28V216h55c6.6 0 11.9-5.3
            11.9-11.9V11.9C216 5.3 210.7 0 204.1 0z"></path></svg>
            <span>Continue with Facebook</span>
            <% end  %>
          </div>
        </div>


  <!-- <div class="btn btn-warning" style="width: 100%;">
    <%#= link_to "SEARCH", load_path %>
  </div> -->
</div>
</div>

app/views/pages/home.html.erb
<div class="video-back">
  <video playsinline autoplay muted loop poster="<%= image_path('background.png') %>" id="doge">
    <source src="https://www.videvo.net/videvo_files/converted/2014_03/preview/Beer_Bubbles_300314__Videvo.mov34510.webm" type="video/webm">
    <source src="https://www.videvo.net/videvo_files/converted/2014_03/videos/Beer_Bubbles_300314__Videvo.mov34510.mp4" type="video/mp4">
    </video>
  </div>


  <div class="home-wrapper">
    <div class="home-content">
      <div id="logo" class="text-center">
        <%= image_tag("Logo pink-1.png",
        alt: "Post Meridiem Logo") %>
      </div>

      <h1 class="text-center">
        your perfect evening<br>
        just around the corner
      </h1>

      <div class="container">
        <div class="row up-down-margin">
          <div class="col-xs-8 col-xs-offset-2">
            <div class="row row-first">
              <%= link_to "LOG IN", new_user_session_path, class: "btn-danger btn-md" %>

              <%= link_to "SIGN UP", new_user_registration_path, class: "btn-danger btn-md" %>
            </div>
          </div>
        </div>

        <div class="row">


          <%= link_to new_user_session_path, class: "facebookLoginBtnMain xLargeFacebookBtn" do %>
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 216 216" class="_55a2"><path fill="white" d="
            M204.1 0H11.9C5.3 0 0 5.3 0 11.9v192.2c0 6.6 5.3 11.9 11.9
            11.9h103.5v-83.6H87.2V99.8h28.1v-24c0-27.9 17-43.1 41.9-43.1
            11.9 0 22.2.9 25.2 1.3v29.2h-17.3c-13.5 0-16.2 6.4-16.2
            15.9v20.8h32.3l-4.2 32.6h-28V216h55c6.6 0 11.9-5.3
            11.9-11.9V11.9C216 5.3 210.7 0 204.1 0z"></path></svg>
            <span>Continue with Facebook</span>
            <% end  %>
          </div>
        </div>


  <!-- <div class="btn btn-warning" style="width: 100%;">
    <%#= link_to "SEARCH", load_path %>
  </div> -->
</div>
</div>

app/views/pages/load.html.erb
<div class="wrapper"
style="height: 100vh; background-color: #EE2B47">

  <div id="title">
    <h1><%= link_to "POST", search_path %></h1>
    <h2>MERIDIEM</h2>
  </div>
</div>

app/views/pages/search.html.erb
<div class="main-wrapper">
    <div class="banner">

        <div class="rectangle-text"><h1>Find quickly near me</h1>

        </div>
    </div>

    <div class="wrapper wrapper-search" >
        <div class="main-card-search">
            <a class="" href="/places?kind=restaurant"></a>
            <div class="card-search" style="
            background-image: linear-gradient(90deg, rgba(255,255,255,0.1) 40%, rgba(3,2,1,0.5) 90%), url(https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNLgpVeHqRwiLfDxVsvXFHYHRePSSM5OR3m1ugkigVHqKT0iaFog);">
            <div class="info-card">
               <div class="card-description">
                <h3 class="card-category">Restaurants</h3>
                <p>Burgers, sushis, healthy food</p>
            </div>
        </div>
    </div>
</div>


<div class="main-card-search">
    <a class="" href="/places?kind=bar"></a>
    <div class="card-search" style="
    background-image: linear-gradient(90deg, rgba(255,255,255,0.1) 40%, rgba(3,2,1,0.5) 90%), url(https://assets.bonappetit.com/photos/57acbeaa1b33404414975151/16:9/w_1200,c_limit/pineapple-hibiscus-cocktail.jpg);">

    <div class="info-card">
     <div class="card-description">
        <h3 class="card-category">Bars</h3>
        <p>Beers, cocktails</p>
    </div>
</div>
</div>
</div>



<div class="main-card-search">
    <a class="" href="/places?kind=cafe"></a>
    <div class="card-search" style="
    background-image: linear-gradient(90deg, rgba(255,255,255,0.1) 40%, rgba(3,2,1,0.5) 90%), url(https://coffee-brewing-methods.com/wp-content/uploads/Latte-art-pexels.jpg);">
    <div class="shapes">
        <div class="triangle"></div>
    </div>
    <div class="info-card">
       <div class="card-description">
           <h3 class="card-category">Cafes</h3>
           <p>Tasty cappucinos, amazing coffees</p>
       </div>
   </div>
</div>
</div>
</div>

</div>

app/views/places/index.html.erb
<style>
  html, body {
  width: 100%;
  height: 100%;
  background-color: #ccccff;
}

svg {
  display: inline-block;
  margin: 3% auto;
  padding: 0px 0px;
  max-width: 60vh;
  position: relative;
  display: inline-block;
  margin: 0 auto;
  padding: 0px;
  top: -350px;
  justify-content: center;
  right: -6%;
}
</style>

<div class="tinder">


  <div class="tinder--cards">
  <div class="last-card" style="display: none; background: url(http://images6.fanpop.com/image/photos/38700000/That-s-All-Folks-the-looney-tunes-show-38740983-500-281.jpg) no-repeat; background-position: center; width: 100vh; height: 100vh";></div>
    <% @places.each do |place|  %>

    <div class="tinder--card">
      <%= link_to place_path(place) do %>

        <% if place.google_data["photos"].size > 0 %>



        <img class="forty-vh" src="<%= place.image_url %>" >

        <% else %>
          <br>
          <br>
          <br>
        <% end %> <%# END of IF  %>

        <!-- <h3>
          <i class="far fa-clock"></i> "5 min" just around the corner
        </h3> -->

        <div class="rating-index">
            <% blank_stars = 5 - place.google_data["rating"].to_i %>
            <% place.google_data["rating"].to_i.times do  %>
              <i class="fas fa-star filledstars"></i>
            <% end %>
            <% blank_stars.times do %>
              <i class="far fa-star blankstars"></i>
            <% end %>
        </div>

        <div class="div-name">
          <%= link_to place.name, place_path(place)  %>
        </div>

      <% end %> <%# END of LINK_TO  %>


      <ul class="list-inline">
        <li>
          <%= link_to place_matches_path(place, {:place => {:place_id =>  place.id, status: "no"}, kind: params[:kind]}), :action => :create, :method => :post do %>
            <i id="cross-icon" class="fas fa-times"></i>
          <% end %>
        </li>
        <li>
          <%= link_to place_path(place) do %>
            <i id="info-icon" class="fas fa-info"></i>
          <% end %>
        </li>
        <li>
          <%= link_to place_matches_path(place, {:place => {:place_id =>  place.id, status: "yes"}, kind: params[:kind] }), :action => :create, :method => :post do %>
            <i id="heart-icon" class="far fa-heart"></i>
          <% end %>
        </li>
      </ul>

    </div>


    <% end %> <%# END of @places.each do |place| %>
  </div>

</div>
    <svg id="Swipe-horizontal_1" style="display:none;" data-name="Swipe horizontal 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 200">
      <path class="hand-x" d="M139.93,113.56l-41.12-6.93V76.08a9.25,9.25,0,0,0-9.25-9.25h0a9.25,9.25,0,0,0-9.25,9.25v57.36L71,122.65c-3.61-3.61-8.44-3.89-13.08,0,0,0-7.24,5.84-3.83,9.25l34,34h42.63a9.25,9.25,0,0,0,9.07-7.43l6.82-34.09A9.28,9.28,0,0,0,139.93,113.56Z"/>
      <g class="swipe-horizontal">
        <path class="line-horizontal" d="M70.85,42c19.69-12.46,37,0,37,0"/>
        <polyline class="arrow-left" points="76.6 46.01 68.37 43.43 68.38 43.41 70.96 35.18"/>
        <polyline class="arrow-right" points="100.21 44.66 108.43 42.08 108.43 42.06 105.85 33.84"/>
      </g>
    </svg>

app/views/places/show.html.erb
<div class="wrapper-show">
  <% if @place.google_data["photos"].size > 0 %>
  <div class="photo-show" style="background: url('<%= asset_url @place.image_url %>') center center no-repeat;">
  </div>
  <% end %>

  <div class="main-place-information">
    <div class="place">

      <div class="title">

        <div class="goto-maps">
          <%= link_to "https://www.google.com/maps/dir/?api=1&destination=#{URI::encode(@place.address)}", target: "_blank" do %>
          <p><i class="fas fa-street-view"></i></p>
          <% end %>
        </div>

        <div class="place-title">
           <div class="rating-show">
        <% blank_stars = 5 - @place.google_data["rating"].to_i %>
        <% @place.google_data["rating"].to_i.times do  %>
        <i class="fas fa-star filledstars"></i>
        <% end %>
        <% blank_stars.times do %>
        <i class="far fa-star blankstars"></i>
        <% end %>
      </div>
          <h2><%= @place.name.capitalize %></h2>

        </div>

        <div>
          <%= link_to place_matches_path(@place, {:place => {:place_id =>  @place.id }}), :action => :create, :method => :post do %>
          <i id="heart-icon" class="far fa-heart"></i>
          <% end %>

        </div>

      </div>
    </div>
  </div>



  <div class="info-description">
    <div class="description">
      <p id="address"><i class="fas fa-map-marker"></i>
        <%= @place.address%>
      </p>

      <p id="phone"><i class="fas fa-phone-volume"></i>
        <%= @place.phone_number%>
      </p>
      <p>
        <%= link_to "Go to website", @place.website, target: "_blank" %>
      </p>
    </div>

    <div class="timetable">
      <!-- <i class="far fa-clock"></i> -->
      <div class='hoursWrapper'>

        <div class="hoursBox">
          <div class='hoursContent'>
            <div class='hoursTitle'>
              <ul class="select-options">
                <% @place.google_data["opening_hours"]["weekday_text"].each do |daytime| %>
                <li>
                  <%= daytime %>
                </li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>


    <% (@place.google_data["reviews"] || []).each do |review| %>
    <hr>

    <div class="review-card">
      <%= image_tag review['profile_photo_url'], size: "40x40", alt: "review profile pic" %>
      <div class="flex-item">
        <p><strong><%= review["author_name"] %></strong></p>

        <% blank_stars = 5 - review["rating"].to_i %>
        <% review["rating"].to_i.times do  %>
        <i class="fas fa-star filledstars"></i>
        <% end %>
        <% blank_stars.times do %>
        <i class="far fa-star blankstars"></i>
        <% end %>


        <% content_text = review["text"] %>


        <% if content_text %>
        <div class="expandable">
          <p class="text-intro"> <%= content_text.first(100) %> <span class="text-all" style="display:none;"> <%= content_text[99..-1]  %> </span>
          </p>
          <% if content_text[99] %>
          <a class="text-show-more" href="#">Show more</a>
          <a class="text-show-less" style="display:none;" href="#">Show less</a>
          <% end %>
        </div>
        <% end %>


      </div>
    </div>
    <% end %>



  </div>
</div>

app/views/shared/_cards.html.erb
<div class="tinder">
  <div class="tinder--status">
    <i class="fa fa-remove"></i>
    <i class="fa fa-heart"></i>
  </div>

  <div class="tinder--cards">
    <div class="tinder--card">
      <img src="https://placeimg.com/600/300/people">
      <h3><%= place.name %></h3>
      <p>This is a demo for Tinder like swipe cards</p>
    </div>

    <!-- <div class="tinder--card">
      <img src="https://placeimg.com/600/300/animals">
      <h3>Demo card 2</h3>
      <p>This is a demo for Tinder like swipe cards</p>
    </div>

    <div class="tinder--card">
      <img src="https://placeimg.com/600/300/nature">
      <h3>Demo card 3</h3>
      <p>This is a demo for Tinder like swipe cards</p>
    </div>

    <div class="tinder--card">
      <img src="https://placeimg.com/600/300/tech">
      <h3>Demo card 4</h3>
      <p>This is a demo for Tinder like swipe cards</p>
    </div>

    <div class="tinder--card">
      <img src="https://placeimg.com/600/300/arch">
      <h3>Demo card 5</h3>
      <p>This is a demo for Tinder like swipe cards</p>
    </div> -->
  </div>

  <div class="tinder--buttons">
    <button id="nope"><i class="fa fa-remove"></i></button>
    <button id="love"><i class="fa fa-heart"></i></button>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to places_path(intro: 1), class: "navbar-wagon-brand" do %>
    <%= image_tag "Logo pink-1.png", class: "logo-navbar" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged I need to replace -->
      <%= link_to image_tag("full_heart_icon.png"), "#", class: "favorites-navbar avatar" %>
      <span class="badge"><%= Match.where(user_id: current_user, status: "yes").count %></span>



      <!-- Avatar with dropdown menu I need to replace -->
      <div class="navbar-wagon-item">
        <div class="dropdown">

          <% fb_url = current_user.facebook_picture_url || "icons_about_user.png" %>
          <%= image_tag fb_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>

          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div> <!-- div class="dropdown" -->
      </div> <!-- div class="navbar-wagon-item" -->

    <% else %>

    <!-- Login link (when logged out) -->
    <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg" style="display: flex;">
<div>
    <% if current_user %>
      <%= link_to search_path do %>
        <i id="search-icon" class="fas fa-search"></i>
      <% end %>

      <%= link_to user_matches_path(current_user.id) do %>
        <i id="icon-matches" class="fab fa-gratipay"></i>

        <span class="badge"><%= Match.where(user_id: current_user, status: "yes").count %></span>

      <% end %>
    <% end %>
</div>
    <div class="dropdown">

      <%= image_tag "icons_about_user.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>

      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Profile</a></li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fas fa-sign-out-alt"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>